name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


env:
  DOTNET_VERSION: 7.0.x
  BUILD_TARGET: .\src\VirtualDesktop.sln


jobs:
  build:
    name: .NET Build
    runs-on: windows-latest
    # Don't build for release the publish workflow will do that to
    if: "!startsWith(github.event.head_commit.message, 'Release v')"
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      
    - name: Build
      run: dotnet build ${{ env.BUILD_TARGET }} -c Release
